# outputs.tf

# Global outputs
output "region" {
  description = "AWS Region to to deploy discovery resources"
  value       = var.show_outputs ? var.region : null
}

output "regions" {
  description = "AWS Regions to to deploy scanning resources"
  value       = var.show_outputs ? var.regions : null
}

# Kinesis module outputs
output "cloudwatch_event_bus_arn" {
  description = "Cloudwatch Event Bus ARN"
  value       = var.show_outputs && var.type == "single" ? module.single[0].cloudwatch_event_bus_arn : null
}

output "cloudwatch_event_rule_arn" {
  description = "Cloudwatch Event Rule ARN"
  value       = var.show_outputs && var.type == "single" ? module.single[0].cloudwatch_event_rule_arn : null
}

output "kinesis_processor_lambda_log_group_name" {
  description = "Kinesis Processor Lambda Cloudwatch Log Group Name"
  value       = var.show_outputs && var.type == "single" ? module.single[0].kinesis_processor_lambda_log_group_name : null
}

output "kinesis_stream_events_role_arn" {
  description = "Kinesis Stream Events Role ARN"
  value       = var.show_outputs && var.type == "single" ? module.single[0].kinesis_stream_events_role_arn : null
}

output "kinesis_firehose_role_arn" {
  description = "Kinesis Firehose Role ARN"
  value       = var.show_outputs && var.type == "single" ? module.single[0].kinesis_firehose_role_arn : null
}

output "kinesis_processor_lambda_execution_role_arn" {
  description = "Kinesis Processor Lambda Execution Role ARN"
  value       = var.show_outputs && var.type == "single" ? module.single[0].kinesis_processor_lambda_execution_role_arn : null
}

output "kinesis_firehose_bucket_name" {
  description = "Kinesis Firehose S3 Bucket Name"
  value       = var.show_outputs && var.type == "single" ? module.single[0].kinesis_firehose_bucket_name : null
}

output "kinesis_processor_lambda_function_arn" {
  description = "Kinesis Processor Lambda Function ARN"
  value       = var.show_outputs && var.type == "single" ? module.single[0].kinesis_processor_lambda_function_arn : null
}

output "kinesis_stream_arn" {
  description = "Kinesis Stream ARN"
  value       = var.show_outputs && var.type == "single" ? module.single[0].kinesis_stream_arn : null
}

output "kinesis_firehose_delivery_stream_arn" {
  description = "Kinesis Firehose Delivery Stream ARN"
  value       = var.show_outputs && var.type == "single" ? module.single[0].kinesis_firehose_delivery_stream_arn : null
}

# Lambda module outputs
output "cspm_external_id" {
  description = "Aqua CSPM External ID generated by the 'generate_cspm_external_id_function' Lambda function"
  value       = var.show_outputs && var.type == "single" ? module.single[0].cspm_external_id : null
}

output "volscan_external_id" {
  description = "Aqua Volume Scanning External ID generated by the 'generate_volscan_external_id_function' Lambda function"
  value       = var.show_outputs && var.type == "single" ? module.single[0].volscan_external_id : null
}

output "is_already_cspm_client" {
  description = "Boolean indicating if the client is already a CSPM client, to be sent to the Autoconnect API"
  value       = var.show_outputs && var.type == "single" ? module.single[0].is_already_cspm_client : null
}

output "cspm_lambda_execution_role_arn" {
  description = "The ARN of the lambda execution IAM role created for the CSPM"
  value       = var.show_outputs && var.type == "single" ? module.single[0].kinesis_processor_lambda_execution_role_arn : null
}

output "cspm_role_arn" {
  description = "The ARN of the IAM role created for the CSPM"
  value       = var.show_outputs && var.type == "single" ? module.single[0].cspm_role_arn : null
}

output "agentless_role_arn" {
  description = "The ARN of the IAM role created for the Agentless Volume Scanning"
  value       = var.show_outputs && var.type == "single" ? module.single[0].agentless_role_arn : null
}

# Stackset module outputs
output "stack_set_name" {
  description = "Name of the CloudFormation StackSet"
  value       = var.show_outputs && var.type == "single" ? module.single[0].stack_set_name : null
}

output "stack_set_admin_role_arn" {
  description = "ARN of the StackSet admin role"
  value       = var.show_outputs && var.type == "single" ? module.single[0].stack_set_admin_role_arn : null
}

output "stack_set_admin_role_name" {
  description = "Name of the StackSet admin role"
  value       = var.show_outputs && var.type == "single" ? module.single[0].stack_set_admin_role_name : null
}

output "stack_set_execution_role_arn" {
  description = "ARN of the StackSet execution role"
  value       = var.show_outputs && var.type == "single" ? module.single[0].stack_set_execution_role_arn : null
}

output "stack_set_execution_role_name" {
  description = "Name of the StackSet execution role"
  value       = var.show_outputs && var.type == "single" ? module.single[0].stack_set_admin_role_name : null
}

output "stack_set_template_url" {
  description = "URL of the CloudFormation template used by the StackSet"
  value       = var.show_outputs && var.type == "single" ? module.single[0].stack_set_template_url : null
}

# Trigger module outputs
output "onboarding_status" {
  description = "Onboarding API Status Result"
  value       = var.type == "single" ? module.single[0].onboarding_status : null
}