# modules/single/outputs.tf

# Kinesis module outputs
output "cloudwatch_event_bus_arn" {
  description = "Cloudwatch Event Bus ARN"
  value       = try(module.kinesis.event_bus_arn, null)
}

output "cloudwatch_event_rule_arn" {
  description = "Cloudwatch Event Rule ARN"
  value       = try(module.kinesis.event_rule_arn, null)
}

output "kinesis_processor_lambda_log_group_name" {
  description = "Kinesis Processor Lambda Cloudwatch Log Group Name"
  value       = try(module.kinesis.kinesis_processor_lambda_log_group_name, null)
}

output "kinesis_stream_events_role_arn" {
  description = "Kinesis Stream Events Role ARN"
  value       = try(module.kinesis.kinesis_stream_events_role_arn, null)
}

output "kinesis_firehose_role_arn" {
  description = "Kinesis Firehose Role ARN"
  value       = try(module.kinesis.kinesis_firehose_role_arn, null)
}

output "kinesis_processor_lambda_execution_role_arn" {
  description = "Kinesis Processor Lambda Execution Role ARN"
  value       = try(module.kinesis.kinesis_processor_lambda_execution_role_arn, null)
}

output "kinesis_firehose_bucket_name" {
  description = "Kinesis Firehose S3 Bucket Name"
  value       = try(module.kinesis.kinesis_firehose_bucket_name, null)
}

output "kinesis_processor_lambda_function_arn" {
  description = "Kinesis Processor Lambda Function ARN"
  value       = try(module.kinesis.kinesis_processor_lambda_function_arn, null)
}

output "kinesis_stream_arn" {
  description = "Kinesis Stream ARN"
  value       = try(module.kinesis.kinesis_stream_arn, null)
}

output "kinesis_firehose_delivery_stream_arn" {
  description = "Kinesis Firehose Delivery Stream ARN"
  value       = try(module.kinesis.kinesis_firehose_delivery_stream_arn, null)
}

# Lambda module outputs
output "cspm_external_id" {
  description = "Aqua CSPM External ID generated by the 'generate_cspm_external_id_function' Lambda function"
  value       = try(module.lambda.cspm_external_id, null)
}

output "volscan_external_id" {
  description = "Aqua Volume Scanning External ID generated by the 'generate_volscan_external_id_function' Lambda function"
  value       = try(module.lambda.volscan_external_id, null)
}

output "cspm_lambda_execution_role_arn" {
  description = "The ARN of the lambda execution IAM role created for the CSPM"
  value       = try(module.lambda.cspm_lambda_execution_role_arn, null)
}

output "cspm_role_arn" {
  description = "The ARN of the IAM role created for the CSPM"
  value       = try(module.lambda.cspm_role_arn, null)
}

output "agentless_role_arn" {
  description = "The ARN of the IAM role created for the Agentless Volume Scanning"
  value       = try(module.lambda.agentless_role_arn, null)
}

output "registry_scanning_role_arn" {
  description = "The ARN of the IAM role created for Registry Scanning"
  value       = try(module.lambda.registry_scanning_role_arn, null)
}

output "serverless_scanning_role_arn" {
  description = "The ARN of the IAM role created for Serverless Scanning"
  value       = try(module.lambda.serverless_scanning_role_arn, null)
}

# Stackset module outputs
output "stack_set_name" {
  description = "Name of the CloudFormation StackSet"
  value       = try(module.stackset.stack_set_name, null)
}

output "stack_set_admin_role_arn" {
  description = "ARN of the StackSet admin role"
  value       = try(module.stackset.stack_set_admin_role_arn, null)
}

output "stack_set_admin_role_name" {
  description = "Name of the StackSet admin role"
  value       = try(module.stackset.stack_set_admin_role_name, null)
}

output "stack_set_execution_role_arn" {
  description = "ARN of the StackSet execution role"
  value       = try(module.stackset.stack_set_execution_role_arn, null)
}

output "stack_set_execution_role_name" {
  description = "Name of the StackSet execution role"
  value       = try(module.stackset.stack_set_execution_role_name, null)
}

output "stack_set_template_url" {
  description = "URL of the CloudFormation template used by the StackSet"
  value       = try(module.stackset.stack_set_template_url, null)
}

# Trigger module outputs
output "onboarding_status" {
  description = "Onboarding API Status Result"
  value       = try(module.trigger.onboarding_status, null)
}
